import { createTypes } from 'reduxsauce';
export default createTypes(`

    SET_SIGNUP_EMAIL
    SIGNIN_USER
    SIGNOUT_USER
    SET_USER_PROFILE

    LOAD_CODE_REQUEST
    LOAD_CODE_SUCCESS
    LOAD_CODE_FAILED

    ES_QUERY_REQUEST
    ES_QUERY_SUCCESS
    ES_QUERY_FAILED

    LOAD_COMPONENT_REQUEST
    LOAD_COMPONENT_SUCCESS
    LOAD_PUBLIC_COMPONENT_SUCCESS
    LOAD_COMPONENT_FAILED

    SET_CODE_DATA
    SET_CODE_EDITOR
    SET_QUESTION_COMMENT_STATUS
    SET_COMPONENT_SELECTION
    SET_OUTPUT
    SET_RUN_BLOCK

    POST_REPLY_REQUEST
    POST_REPLY_SUCCESS
    POST_REPLY_FAILED

    POST_QUESTION_REQUEST
    POST_QUESTION_SUCCESS
    POST_QUESTION_FAILED

    RUN_CODE_REQUEST
    RUN_CODE_SUCCESS
    RUN_CODE_FAILED

    LOAD_COMMENTS_REQUEST
    LOAD_COMMENTS_SUCCESS
    LOAD_COMMENTS_FAILED

    SAVE_CODE_REQUEST
    SAVE_CODE_SUCCESS
    SAVE_CODE_FAILED

    SAVE_CODE_PUBLIC_REQUEST
    SAVE_CODE_PUBLIC_SUCCESS
    SAVE_CODE_PUBLIC_FAILED

    VOTE_UP_REQUEST
    VOTE_DOWN_REQUEST
`)
